server.port=5030
spring.application.name=AAS Discovery Service
basyx.aasdiscoveryservice.name=aas-discovery-service
basyx.backend=MongoDB
basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
spring.data.mongodb.host=mongodb
spring.data.mongodb.database=aas-discovery
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
