services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo:0.3.1.284-aasv3-alpha-latest 
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/AasxServerBlazor/aasxs
    command: --no-security --rest --external-blazor http://localhost:5001
    networks:
      - agentic-net

  neo4j:
    container_name: neo4j
    image: neo4j:5
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password123"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    networks:
      - agentic-net

  agent-runtime:
    container_name: agent-runtime
    build: ./agent-runtime
    restart: unless-stopped
    depends_on:
      - aasx-server
      - neo4j
    ports:
      - "8000:8000"
    networks:
      - agentic-net
    env_file:
      - .env
  aasx-mcp-service:
    profiles: ["http"]  # Only starts if you run: docker compose --profile http up
    build: ./agent-runtime
    container_name: aasx-mcp-service
    command: python -m src.mcp.aasx.aasx_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MCP_CONNECTION_MODE=http
      - PORT=8080
      - AAS_BASE_URL=http://aasx-server:5001
    depends_on:
      - aasx-server
    networks:
      - agentic-net
    

networks:
  agentic-net:
    name: agentic-net
    driver: bridge
